name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  firebase_database: ^11.0.2
  cloud_firestore: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Mulish
      fonts:
      - asset: fonts/Mulish.ttf
  assets:
  - images/
  - fonts/
  
