name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  firebase_auth: ^5.1.1
  firebase_messaging: ^15.0.2
  firebase_database: ^11.0.2
  
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  modal_progress_hud_alt: ^1.0.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.0
  faker: ^2.1.0
  jiffy: ^6.3.1
  stream_chat_flutter_core: ^8.0.0
  logger: ^2.4.0
  cloud_functions: ^5.0.4
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Mulish
      fonts:
      - asset: fonts/Mulish.ttf
  assets:
  - images/
  - fonts/
